from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

from .contracts import (
    DailySurveillanceSubmission,
    Department,
    EventCase,
    EventReport,
    Facility,
    PilotStateCell,
    PolicyRecord,
    SafetySignal,
    SurveillanceSnapshot,
    UserIdentity,
)


def build_demo_snapshot() -> SurveillanceSnapshot:
    now = datetime(2026, 3, 8, 9, 0, 0, tzinfo=timezone.utc)
    facilities = [
        Facility(
            facility_id="FAC-TMK-001",
            name="Shridevi Institute of Medical Sciences and Research Hospital",
            state="Karnataka",
            district="Tumkur",
            ownership="teaching",
            level="medical_college",
            abdm_registry_ready=True,
            registry_source="abdm_seed",
        ),
        Facility(
            facility_id="FAC-DLH-014",
            name="District Hospital Jaipur Sentinel Site",
            state="Rajasthan",
            district="Jaipur",
            ownership="public",
            level="district_hospital",
            abdm_registry_ready=True,
            registry_source="state_registry",
        ),
        Facility(
            facility_id="FAC-KOL-022",
            name="Metro Multispeciality Safety Network Site",
            state="West Bengal",
            district="Kolkata",
            ownership="private",
            level="private_hospital",
            abdm_registry_ready=False,
            registry_source="manual",
        ),
    ]
    reports = [
        EventReport(
            report_id="EVT-IND-1001",
            event_date=date(2026, 3, 6),
            reported_at=now - timedelta(hours=20),
            facility_id="FAC-TMK-001",
            patient_context="Adult inpatient, post-operative ward",
            domain="medication",
            deviation_class="contradiction",
            severity="moderate",
            process_stage="order -> verification -> administration",
            summary="Beta-lactam order placed despite allergy documentation mismatch.",
            immediate_action="Order held and pharmacist alerted.",
            status="investigating",
            assigned_to="State clinical pharmacist reviewer",
            state_cell="Karnataka state cell",
        ),
        EventReport(
            report_id="EVT-IND-1002",
            event_date=date(2026, 3, 5),
            reported_at=now - timedelta(days=1, hours=3),
            facility_id="FAC-DLH-014",
            patient_context="Emergency department, suspected sepsis",
            domain="deterioration",
            deviation_class="harmful_delay",
            severity="severe",
            process_stage="recognition -> escalation -> treatment",
            summary="Delayed escalation after repeated abnormal vitals and lactate trigger.",
            immediate_action="Rapid response review initiated.",
            status="triaged",
            assigned_to="Rajasthan state patient safety cell",
            state_cell="Rajasthan state cell",
        ),
        EventReport(
            report_id="EVT-IND-1003",
            event_date=date(2026, 3, 4),
            reported_at=now - timedelta(days=2),
            facility_id="FAC-KOL-022",
            patient_context="Outpatient imaging follow-up",
            domain="lab_radiology",
            deviation_class="closure_failure",
            severity="moderate",
            process_stage="result -> acknowledgement -> follow-up -> closure",
            summary="Critical imaging result acknowledged but no documented clinician follow-up.",
            immediate_action="Case escalated to facility safety officer.",
            status="reported",
        ),
    ]
    signals = [
        SafetySignal(
            signal_id="SIG-KA-01",
            title="Medication allergy contradiction cluster",
            scope="facility",
            state="Karnataka",
            district="Tumkur",
            domain="medication",
            deviation_class="contradiction",
            severity="moderate",
            reports_linked=4,
            owner_role="Facility medication safety lead",
            next_action="Review allergy documentation workflow and CPOE reconciliation.",
            status="investigate",
        ),
        SafetySignal(
            signal_id="SIG-IN-02",
            title="Delayed escalation in deterioration pathways",
            scope="state",
            state="Rajasthan",
            district=None,
            domain="deterioration",
            deviation_class="harmful_delay",
            severity="severe",
            reports_linked=9,
            owner_role="State patient safety intelligence cell",
            next_action="Conduct focused review of ED escalation and sepsis bundle completion.",
            status="escalated",
        ),
    ]
    policies = [
        PolicyRecord(
            policy_id="POL-IND-001",
            title="National minimum patient safety dataset v1",
            state="approved_pilot",
            validation_phase="controlled_pilot",
            approver="National steering group",
            activation_scope="Sentinel states",
            last_updated=date(2026, 3, 1),
        ),
        PolicyRecord(
            policy_id="POL-IND-002",
            title="Sentinel event 24-hour reporting rule",
            state="approved_production",
            validation_phase="scale_up",
            approver="National steering group",
            activation_scope="National",
            last_updated=date(2026, 2, 20),
        ),
    ]
    return SurveillanceSnapshot(
        overview={
            "reporting_period": "March 2026 pilot snapshot",
            "facilities_onboarded": 42,
            "states_covered": 8,
            "reports_received": 186,
            "open_investigations": 31,
            "escalated_signals": 7,
            "sentinel_events": 3,
            "validation_phase": "controlled_pilot",
        },
        facilities=facilities,
        reports=reports,
        signals=signals,
        policies=policies,
    )


def build_demo_users() -> list[UserIdentity]:
    return [
        UserIdentity(
            user_id="demo-fso-ka",
            name="Karnataka Facility Safety Officer",
            role="facility_safety_officer",
            state="Karnataka",
            district="Tumkur",
            facility_id="FAC-TMK-001",
            username="ka-fso",
        ),
        UserIdentity(
            user_id="demo-ed-ka",
            name="Tumkur Emergency Department Reporter",
            role="facility_reporter",
            state="Karnataka",
            district="Tumkur",
            facility_id="FAC-TMK-001",
            department_id="DEPT-TMK-ED",
            username="tmk-ed",
        ),
        UserIdentity(
            user_id="demo-icu-ka",
            name="Tumkur ICU Reporter",
            role="facility_reporter",
            state="Karnataka",
            district="Tumkur",
            facility_id="FAC-TMK-001",
            department_id="DEPT-TMK-ICU",
            username="tmk-icu",
        ),
        UserIdentity(
            user_id="demo-state-ka",
            name="Karnataka State Cell Analyst",
            role="state_cell_analyst",
            state="Karnataka",
            username="state-ka",
        ),
        UserIdentity(
            user_id="demo-state-rj",
            name="Rajasthan State Cell Analyst",
            role="state_cell_analyst",
            state="Rajasthan",
            username="state-rj",
        ),
        UserIdentity(
            user_id="demo-national",
            name="National Surveillance Analyst",
            role="national_analyst",
            username="national",
        ),
        UserIdentity(
            user_id="demo-admin",
            name="Governance Administrator",
            role="governance_admin",
            username="admin",
        ),
    ]


def build_demo_state_cells() -> list[PilotStateCell]:
    return [
        PilotStateCell(
            state_cell_id="STATE-KA",
            state="Karnataka",
            nodal_unit="State patient safety intelligence cell",
            lead_name="State Quality and Safety Lead",
            status="pilot",
            facilities_mapped=12,
        ),
        PilotStateCell(
            state_cell_id="STATE-RJ",
            state="Rajasthan",
            nodal_unit="State patient safety intelligence cell",
            lead_name="State Epidemiology and Quality Lead",
            status="pilot",
            facilities_mapped=9,
        ),
    ]


def build_demo_departments() -> list[Department]:
    return [
        Department(department_id="DEPT-TMK-ED", facility_id="FAC-TMK-001", name="Emergency Department", category="clinical"),
        Department(department_id="DEPT-TMK-ICU", facility_id="FAC-TMK-001", name="ICU", category="clinical"),
        Department(department_id="DEPT-TMK-OT", facility_id="FAC-TMK-001", name="Operation Theatre", category="clinical"),
        Department(department_id="DEPT-TMK-QA", facility_id="FAC-TMK-001", name="Quality Cell", category="quality"),
        Department(department_id="DEPT-JPR-ED", facility_id="FAC-DLH-014", name="Emergency Department", category="clinical"),
        Department(department_id="DEPT-KOL-RAD", facility_id="FAC-KOL-022", name="Radiology", category="support"),
    ]


def build_demo_daily_submissions() -> list[DailySurveillanceSubmission]:
    today = date(2026, 3, 8)
    now = datetime(2026, 3, 8, 9, 0, 0, tzinfo=timezone.utc)
    return [
        DailySurveillanceSubmission(
            submission_id="SUB-TMK-001",
            submission_date=today,
            facility_id="FAC-TMK-001",
            department_id="DEPT-TMK-ED",
            submitted_by="demo-ed-ka",
            patient_days=118,
            admissions=42,
            discharges=39,
            surgeries=0,
            deliveries=0,
            critical_results_count=4,
            near_misses=4,
            no_harm_events=2,
            harm_events=1,
            severe_events=0,
            medication_events=2,
            procedure_events=0,
            infection_events=0,
            diagnostic_events=1,
            staffing_shortfall_flag=True,
            crowding_flag=True,
            system_downtime_flag=False,
            escalation_required=False,
            notes="High near-miss load during evening shift handover.",
            created_at=now,
            updated_at=now,
        ),
        DailySurveillanceSubmission(
            submission_id="SUB-TMK-002",
            submission_date=today,
            facility_id="FAC-TMK-001",
            department_id="DEPT-TMK-ICU",
            submitted_by="demo-icu-ka",
            patient_days=36,
            admissions=9,
            discharges=7,
            surgeries=2,
            deliveries=0,
            critical_results_count=3,
            near_misses=2,
            no_harm_events=1,
            harm_events=1,
            severe_events=1,
            medication_events=1,
            procedure_events=0,
            infection_events=1,
            diagnostic_events=0,
            staffing_shortfall_flag=False,
            crowding_flag=False,
            system_downtime_flag=False,
            escalation_required=True,
            notes="One deterioration escalation breach triggered review.",
            created_at=now,
            updated_at=now,
        ),
    ]


def build_demo_event_cases() -> list[EventCase]:
    now = datetime(2026, 3, 8, 9, 0, 0, tzinfo=timezone.utc)
    return [
        EventCase(
            case_id="CASE-TMK-1001",
            source_mode="manual_event_report",
            created_at=now - timedelta(hours=10),
            updated_at=now - timedelta(hours=4),
            facility_id="FAC-TMK-001",
            department_id="DEPT-TMK-ED",
            report_id="EVT-IND-1001",
            event_timestamp=now - timedelta(hours=16),
            encounter_setting="emergency",
            shift="evening",
            patient_age_band="45-64",
            patient_sex="female",
            special_population_flags=[],
            encounter_id_local="TMK-ER-10291",
            high_risk_flag=True,
            domain="medication",
            deviation_class="contradiction",
            process_stage="order verification",
            event_type="allergy contraindication order",
            actual_harm="No harm reached patient",
            potential_harm="Severe allergic reaction",
            severity_level="moderate",
            preventability_rating="high",
            detectability_rating="high",
            recurrence_flag=True,
            event_summary="Antibiotic order conflicted with allergy history until pharmacist interception.",
            what_was_expected="Allergy conflict should block ordering at verification stage.",
            what_happened="Order proceeded and was intercepted only during pharmacy verification.",
            immediate_action_taken="Order held, prescriber contacted, alternate antibiotic chosen.",
            evidence_source="manual narrative + pharmacy order review",
            linked_system_trace_id="SC-TRACE-9001",
            linked_policy_version="POL-IND-001",
            contributing_factors=["documentation_quality", "handover_communication", "human_factor_cognitive"],
            triage_status="investigating",
            investigation_method="mini RCA",
            root_cause_category="documentation mismatch",
            corrective_action="Add allergy reconciliation checkpoint in ED admission workflow.",
            preventive_action="Deploy allergy contradiction rules from SentinelCare once connected.",
            owner_assigned="Karnataka Facility Safety Officer",
            due_date=date(2026, 3, 12),
            closure_status="open",
        ),
        EventCase(
            case_id="CASE-JPR-2001",
            source_mode="sentinelcare_detected_event",
            created_at=now - timedelta(days=1),
            updated_at=now - timedelta(hours=6),
            facility_id="FAC-DLH-014",
            department_id="DEPT-JPR-ED",
            report_id="EVT-IND-1002",
            event_timestamp=now - timedelta(days=1, hours=5),
            encounter_setting="emergency",
            shift="night",
            patient_age_band="18-44",
            patient_sex="male",
            special_population_flags=["critical_care"],
            encounter_id_local="JPR-ED-77811",
            high_risk_flag=True,
            domain="deterioration",
            deviation_class="harmful_delay",
            process_stage="recognition and escalation",
            event_type="sepsis escalation delay",
            actual_harm="Delayed antibiotic and fluid bundle initiation",
            potential_harm="Shock and ICU transfer",
            severity_level="severe",
            preventability_rating="high",
            detectability_rating="moderate",
            recurrence_flag=False,
            event_summary="Sepsis pathway breach detected after repeated abnormal vitals and delayed escalation.",
            what_was_expected="Escalation within protocol window after vital sign trigger.",
            what_happened="Escalation delayed beyond threshold and senior review was late.",
            immediate_action_taken="Rapid response activated and state review initiated.",
            evidence_source="sentinelcare trace + vital sign stream",
            linked_system_trace_id="SC-TRACE-9018",
            linked_policy_version="POL-IND-002",
            contributing_factors=["staffing_workload", "protocol_nonadherence", "diagnostic_delay"],
            triage_status="actioned",
            investigation_method="full RCA",
            root_cause_category="escalation pathway breach",
            corrective_action="Mandatory sepsis escalation timer in ED.",
            preventive_action="Statewide silent-mode deterioration monitor.",
            owner_assigned="Rajasthan State Cell Analyst",
            due_date=date(2026, 3, 10),
            closure_status="open",
            ai_summary="High-priority deterioration case with repeated escalation opportunity missed.",
            ai_confidence=0.86,
            ai_provider="openai",
            ai_model="gpt-4.1-mini",
        ),
    ]
